### ISSUE TITLE
Add sone screenshots

### ISSUE THREAD

**Issue by fabiocaccamo** [thomst/django-more-admin-filters#1]
Hello, from the description this library looks promising, I will try it soon. Could you add some screenshots of the different admin filters in the README.

**Comment by thomst** [comment]
@fabiocaccamo Hi. You can easily try out the admin filters by running the testapp:
```
git clone https://github.com/thomst/django-more-admin-filters.git
cd django-more-admin-filters/tests/
python manage.py migrate
python manage.py createtestdata
python manage.py runserver
```
Then you can login at _localhost:8000_ as _admin_ with password _adminpassword_ and checkout all the filters for _ModelA_.
