### ISSUE TITLE
Dependency conflicts

### ISSUE THREAD

**Issue by Enrikaa** [thomst/django-more-admin-filters#10]
Hello!

Thanks for creating this module. It helped a lot to make the Django admin filters more functional. Unfortunately, we can't use it in latest Django versions.

Right now this lib only supports Django `Django>=1.11,<=3.2`, which means it supports max `3.2.0` version. Right now there is latest 3.2.5, so there are dependency conflicts when we want to use latest versions.

**Expected behavior**
Library should support latest Django versions

<img width="384" alt="Screenshot 2021-07-23 at 20 31 15" src="https://user-images.githubusercontent.com/33634122/126819678-be183cde-b641-49c2-a0ad-6f2b2ab01ef2.png">

**Comment by thomst** [comment]
@Enrikaa Thanks for pointing out. I fixed this and released version 1.3.
