### ISSUE TITLE
must inherit from 'FieldListFilter'

### ISSUE THREAD

**Issue by frnhr** [thomst/django-more-admin-filters#5]
I'm getting an error for `BooleanAnnotationFilter`.

Using it like:
``` python
class SomethingAdmin(admin.ModelAdmin):
    ...
    list_filters = (
        ("my_annotation", BooleanAnnotationFilter),
        ...  # other filters
    )
```

manage.py fails on checks, with:

```
ERRORS:
<class 'myapp.admin.SomethingAdmin'>: (admin.E115) The value of 'list_filter[0][1]' must inherit from 'FieldListFilter'.
```

Using Django 3.1.10.

**Comment by frnhr** [comment]
Actually never mind, I was holding it wrong. The correct usage is:
``` python

    list_filters = (
        BooleanAnnotationFilter.init("my_annotation"),
        ...  # other filters
    )
```

Could use an example of this type of filter in the README.md...

**Comment by thomst** [comment]
@frnhr You're right. The AnnotationFilter part is worth to be mentioned within the README. Just updated it. Thanks.
