### ISSUE TITLE
Django 3.1 not supported when installing via pip, despite setup.py/docs

### ISSUE THREAD

**Issue by PorridgeBear** [thomst/django-more-admin-filters#6]
I note that the sources suggest Django 3.1 support was officially added, e.g. in setup.py

`
   install_requires=[
        "Django>=1.11,<=3.1",
    ],
`

but my attempt to pip install the module results in Django 3.1 being uninstalled and replaced with Django 3.0 (see below - the version resolution is looking for Django <= 3.0).

`
root@48e275c6da7e:/code# pip install django-more-admin-filters
Collecting django-more-admin-filters
  Downloading django_more_admin_filters-1.0-py3-none-any.whl (8.5 kB)
Collecting Django<=3.0,>=1.11
  Downloading Django-3.0-py3-none-any.whl (7.4 MB)
     |████████████████████████████████| 7.4 MB 6.6 MB/s 
Requirement already satisfied: pytz in /usr/local/lib/python3.9/site-packages (from Django<=3.0,>=1.11->django-more-admin-filters) (2021.1)
Requirement already satisfied: sqlparse>=0.2.2 in /usr/local/lib/python3.9/site-packages (from Django<=3.0,>=1.11->django-more-admin-filters) (0.4.1)
Requirement already satisfied: asgiref~=3.2 in /usr/local/lib/python3.9/site-packages (from Django<=3.0,>=1.11->django-more-admin-filters) (3.3.1)
Installing collected packages: Django, django-more-admin-filters
  Attempting uninstall: Django
    Found existing installation: Django 3.1.6
    Uninstalling Django-3.1.6:
      Successfully uninstalled Django-3.1.6
Successfully installed Django-3.0 django-more-admin-filters-1.0
`

Am I installing this incorrectly I wonder?

**Comment by thomst** [comment]
@PorridgeBear Sorry. My fault. I forgot to push the latest version on pypi.org. Now it should work! Thanks for reminding me.
