### ISSUE TITLE
Django 3.2 support

### ISSUE THREAD

**Issue by stephenlutes** [thomst/django-more-admin-filters#7]
With Django 3.2 being out for a few months, support for it would be nice.

I have updated the necessary pieces to support it, and run the tests (minus the tests for Python3.4, I am going to spin up a VM this weekend to run those tests). I would be glad to create a pull request once I have run the 3.4 tests.

**Comment by thomst** [comment]
@stephenlutes Great! Very welcome.

**Comment by stephenlutes** [comment]
I was unable to get a working test environment set up for Python 3.4, but everything from 3.5 on passes the tests. I created the pull request, #8. Given that Python 3. 4 has reached end of life, is support for it still needed?

**Comment by thomst** [comment]
> I was unable to get a working test environment set up for Python 3.4, but everything from 3.5 on passes the tests. I created the pull request, #8. Given that Python 3. 4 has reached end of life, is support for it still needed?

No. We can skip python 3.4.

**Comment by stephenlutes** [comment]
Then pull request #8 successfully adds support for Django 3.2 and Python 3.9.

**Comment by thomst** [comment]
I released version 1.2 now, which includes support for Django 3.2.
Thank you for your help
